### PR TITLE
Print the kind of exception we caught.

### PR DESCRIPTION
**Pull request by obino**
We now at least print the kind of exception we caught. Also make sure we
store the appcontroller crashlog for later viewing.

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/733/

this run is not against master, so we can collect some crashlog for sure to see if it works.

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/742/

**Comment by menivaitsi** [comment]
Is there an example in the build log?

**Comment by obino** [comment]
@menivaitsi  yes, if you look at https://ocd.appscale.com:8080/job/Hawkeye/2667/console and search for 

Saw Exception while looking for UAServer

you will see that's there (ie we capture the exception message).

**Pull request merged**
