### PR TITLE
Don't scp unused certificates

### PR DESCRIPTION
**Pull request by obino**

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2168/

**Comment by cdonati** [comment]
Does the build for this branch need to use https://github.com/AppScale/appscale/pull/2215 as the AppScale branch?

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2169

**Comment by obino** [comment]
@cdonati Yes you are correct. This branch works together with https://github.com/AppScale/appscale/pull/2215

**Comment by obino** [comment]
OCD run with https://github.com/AppScale/appscale/pull/2215 https://ocd.appscale.com:8080/job/Daily%20Build/2172/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Create-EC2-Image/204/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Create-EC2-Image/

Previous link was with wrong branch

**Comment by menivaitsi** [comment]
@obino well this link is without the build #... 😈

**Pull request merged**
