### PR TITLE
AWS EC2 instance types

### PR DESCRIPTION
**Pull request by menivaitsi**
OCD: https://ocd.appscale.com:8080/job/Daily%20Build/846/

### CODE REVIEW

**Comment by obino** [comment]
We still use c1.medium in our euca cluster. We can modify it tomorrow so we can merge this.

**Comment by menivaitsi** [comment]
OCD: https://ocd.appscale.com:8080/job/Daily%20Build/864/

**Comment by menivaitsi** [comment]
OCD: https://ocd.appscale.com:8080/job/Daily%20Build/865/

**Comment by menivaitsi** [comment]
OCD: https://ocd.appscale.com:8080/job/Daily%20Build/872/

**Pull request merged**
